version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-aob
    environment:
      POSTGRES_DB: aob
      POSTGRES_USER: aob
      POSTGRES_PASSWORD: aob@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aob-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak-aob
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/aob
      KC_DB_USERNAME: aob
      KC_DB_PASSWORD: aob@123
    volumes:
      - ./keycloak/realm-aob.json:/opt/keycloak/data/import/realm-aob.json
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - aob-net

  backend:
    build:
      context: src/main/docker
      dockerfile: main/docker/Dockerfile.jvm
    container_name: backend-aob
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/aob
      QUARKUS_DATASOURCE_USERNAME: aob
      QUARKUS_DATASOURCE_PASSWORD: aob@123
      QUARKUS_HTTP_PORT: 8081
      KEYCLOAK_URL: http://keycloak:8080/realms/aob
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - keycloak
    networks:
      - aob-net

volumes:
  postgres_data:

networks:
  aob-net:
    driver: bridge
